/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  LooneySwapPair,
  LooneySwapPairInterface,
} from "../LooneySwapPair";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_token0",
        type: "address",
      },
      {
        internalType: "address",
        name: "_token1",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "getReserves",
    outputs: [
      {
        internalType: "uint256",
        name: "_reserve0",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_reserve1",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "reserve0",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "reserve1",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "token0",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "token1",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506040516103ac3803806103ac833981810160405281019061003291906100cf565b816000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555080600160006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055505050610154565b6000815190506100c98161013d565b92915050565b600080604083850312156100e257600080fd5b60006100f0858286016100ba565b9250506020610101858286016100ba565b9150509250929050565b60006101168261011d565b9050919050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b6101468161010b565b811461015157600080fd5b50565b610249806101636000396000f3fe608060405234801561001057600080fd5b50600436106100575760003560e01c80630902f1ac1461005c5780630dfe16811461007b578063443cb4bc146100995780635a76f25e146100b7578063d21220a7146100d5575b600080fd5b6100646100f3565b6040516100729291906101ae565b60405180910390f35b610083610104565b6040516100909190610178565b60405180910390f35b6100a1610128565b6040516100ae9190610193565b60405180910390f35b6100bf61012e565b6040516100cc9190610193565b60405180910390f35b6100dd610134565b6040516100ea9190610178565b60405180910390f35b600080600254915060035490509091565b60008054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b60025481565b60035481565b600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b610163816101d7565b82525050565b61017281610209565b82525050565b600060208201905061018d600083018461015a565b92915050565b60006020820190506101a86000830184610169565b92915050565b60006040820190506101c36000830185610169565b6101d06020830184610169565b9392505050565b60006101e2826101e9565b9050919050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b600081905091905056fea2646970667358221220b9cffc0f7bfd5a40db157d268bb32a11fc0a9348a916b5b058142278f005062864736f6c63430008040033";

export class LooneySwapPair__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    _token0: string,
    _token1: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<LooneySwapPair> {
    return super.deploy(
      _token0,
      _token1,
      overrides || {}
    ) as Promise<LooneySwapPair>;
  }
  getDeployTransaction(
    _token0: string,
    _token1: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(_token0, _token1, overrides || {});
  }
  attach(address: string): LooneySwapPair {
    return super.attach(address) as LooneySwapPair;
  }
  connect(signer: Signer): LooneySwapPair__factory {
    return super.connect(signer) as LooneySwapPair__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LooneySwapPairInterface {
    return new utils.Interface(_abi) as LooneySwapPairInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LooneySwapPair {
    return new Contract(address, _abi, signerOrProvider) as LooneySwapPair;
  }
}
